// AuthNames

export const AUTH_USER = "AUTH_USER"

export const AUTH_LOGOUT_LOAD = "AUTH_LOGOUT_LOAD"

export const AUTH_LOGOUT_FN = "AUTH_LOGOUT_FN"

export const AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS"

export const AUTH_LOGOUT_FAIL = "AUTH_LOGOUT_FAIL"

// auth check user authentication

export const JWT_COOKIE_CHECKER_FN = "JWT_COOKIE_CHECKER_FN"

export const JWT_COOKIE_CHECKER_LOAD = "JWT_COOKIE_CHECKER_LOAD"

export const JWT_COOKIE_CHECKER_FAIL = "JWT_COOKIE_CHECKER_FAIL"

export const JWT_COOKIE_CHECKER_SUCCESS = "JWT_COOKIE_CHECKER_SUCCESS"

//  profile page

export const UPDATE_PROFILE_UPDATED_DATA = "UPDATE_PROFILE_UPDATED_DATA" // FORM DATA

export const UPDATE_PROFILE_LOAD = "UPDATE_PROFILE_LOAD"

export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL"

export const UPDATE_PROFILE_SAVED_DATA = "UPDATE_PROFILE_SAVED_DATA"

// CONFIRMATION

export const CONFIRMATION_PROCESS_LOAD = "CONFIRMATION_PROCESS_LOAD"

export const CONFIRMATION_PROCESS_FAIL = "CONFIRMATION_PROCESS_FAIL"

export const CONFIRMATION_PROCESS_STATUS = "CONFIRMATION_PROCESS_STATUS"

export const FLASH_STATE = "FLASH_STATE"
